### ISSUE TITLE
Bug when coming back from a beer description

### ISSUE THREAD

**Issue by RasCarlito** [deanhume/beer#1]
Hello!

First off, very nice article on implementing service workers and even more so when the app you built talks about beers!

Just wanted to point out that the link `Return to beer styles` at the bottom of a beer description (which takes us back to the beer style page) isn't working as it should.

For example: https://deanhume.github.io/beer/beer.html?id=0&styleId=2&pageId=null

When clicking the link at the bottom of the page it loads the url https://deanhume.github.io/beer/style.html?id=2&pageId=null which shows a never ending loader :cry: 

Without the `pageId=null` query parameter the page works as intended :tada: 

Hope this helps a bit. Cheers! :beers:

**Comment by deanhume** [comment]
Hey @rascarlito

Thanks so much for submitting this issue. I will take a look into it!

**Comment by deanhume** [comment]
All sorted in the latest change - thank you again 👍
